# SPDX-FileCopyrightText: 2023 Sidings Media
# SPDX-License-Identifier: MIT

get:
  description: This OpenAPI specification
  tags:
    - docs
  responses:
    '200':
      description: OpenAPI 3.0 specification
      content:
        application/json:
          schema:
            $ref: https://spec.openapis.org/oas/3.0/schema/2021-09-28
    5XX:
      $ref: ../components/responses/ServerError.yaml
